name: hosts_el
description: "Application Flutter pour la gestion hôtelière."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1 # Updated version
  firebase_auth: ^5.5.1 # Updated version
  cloud_firestore: ^5.6.5 # Updated version
  provider: ^6.1.1
  firebase_database: ^11.3.4 # Updated version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg
